version: '3.8'
services:
  cadastral:
    build: ./app_cadastral
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    networks:
      - mynetwork
      
  serverv_request:
    build: ./other_server
    restart: always
    ports:
      - "8080:8080"
    networks:
      - mynetwork

networks:
  mynetwork: